resources::prezzovaschette::PrezzoVaschette
final Float resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaPiccola
Rappresenta il prezzo di una vaschetta piccola
Referenced by resources.prezzovaschette.PrezzoVaschette.PrezzoVaschette, resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaPiccola.
final Float resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaMedia
Rappresenta il prezzo di una vaschetta media
Referenced by resources.prezzovaschette.PrezzoVaschette.PrezzoVaschette, resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaMedia.
final Float resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaGrande
Rappresenta il prezzo di una vaschetta grande
Referenced by resources.prezzovaschette.PrezzoVaschette.PrezzoVaschette, resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaGrande.
resources.prezzovaschette.PrezzoVaschette.PrezzoVaschette(Float prezzoVaschettaPiccola, Float prezzoVaschettaMedia, Float prezzoVaschettaGrande)
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe prezzoVaschettaPiccola Il prezzo di una vaschetta piccola prezzoVaschettaMedia Il prezzo di una vaschetta media prezzoVaschettaGrande Il prezzo di una vaschetta grande PrezzoVaschette.prezzoVaschettaPiccola PrezzoVaschette.prezzoVaschettaMedia PrezzoVaschette.prezzoVaschettaGrande
References resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaGrande, resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaMedia, resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaPiccola.
Float resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaPiccola()
Ritorna il valore dell'attributo PrezzoVaschette.prezzoVaschettaPiccola.
Il valore dell'attributo PrezzoVaschette.prezzoVaschettaPiccola PrezzoVaschette.prezzoVaschettaPiccola
References resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaPiccola.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer.
Float resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaMedia()
Ritorna il valore dell'attributo PrezzoVaschette.prezzoVaschettaMedia.
Il valore dell'attributo PrezzoVaschette.prezzoVaschettaMedia PrezzoVaschette.prezzoVaschettaMedia
References resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaMedia.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer.
Float resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaGrande()
Ritorna il valore dell'attributo PrezzoVaschette.prezzoVaschettaGrande.
Il valore dell'attributo PrezzoVaschette.prezzoVaschettaGrande PrezzoVaschette.prezzoVaschettaGrande
References resources.prezzovaschette.PrezzoVaschette.prezzoVaschettaGrande.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer.