resources::ordine::xml::parserxml::ParserXMLOrdine
ArrayList<Ordine> resources.ordine.xml.parserxml.ParserXMLOrdine.parsingResult
Lista di oggetti convertiti da "nodi dell'albero DOM"
Referenced by resources.ordine.xml.parserxml.ParserXMLOrdine.parseDocument.
final JList resources.ordine.xml.parserxml.ParserXMLOrdine.jListListaPredefinitaGusti
Referenced by resources.ordine.xml.parserxml.ParserXMLOrdine.ParserXMLOrdine.
resources.ordine.xml.parserxml.ParserXMLOrdine.ParserXMLOrdine(JList jListListaPredefinitaGusti)
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe jSpinnerVaschettaPiccola Riferimento allo spinner InterfacciaPrincipaleGelataio.jSpinnerVaschettaPiccola per ottenere il prezzo delle vaschette piccole per procedere con il calcolo del Ordine.prezzoTotale jSpinnerVaschettaMedia Riferimento allo spinner InterfacciaPrincipaleGelataio.jSpinnerVaschettaMedia per ottenere il prezzo delle vaschette medie per procedere con il calcolo del Ordine.prezzoTotale jSpinnerVaschettaGrande Riferimento allo spinner InterfacciaPrincipaleGelataio.jSpinnerVaschettaGrande per ottenere il prezzo delle vaschette grandi per procedere con il calcolo del Ordine.prezzoTotale ParserXMLOrdine.parsingResult ParserXMLOrdine.jSpinnerVaschettaPiccola ParserXMLOrdine.jSpinnerVaschettaMedia ParserXMLOrdine.jSpinnerVaschettaGrande
References resources.ordine.xml.parserxml.ParserXMLOrdine.jListListaPredefinitaGusti.
ArrayList<Ordine> resources.ordine.xml.parserxml.ParserXMLOrdine.parseDocument(String path)
Effettua il parsing del documento XML di cui viene specificato il path.
path Path del file XML del quale effettuare il parsing Lista di oggetti convertiti da "nodi dell'albero DOM" ParserConfigurationException SAXException IOException ParseException ParserXMLOrdine.parsingResult
References resources.ordine.xml.parserxml.ParserXMLOrdine.parsingResult, resources.ordine.xml.parserxml.ParserXMLOrdine.put.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonScaricaCronologiaOrdinazioniActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer, resources.ordine.OrdineUpdater.run.
void resources.ordine.xml.parserxml.ParserXMLOrdine.put(Document document, Element rootTag, Element singleTag)
Converte un "nodo dell'albero DOM" in oggetto.
singleTag Nodo dell'albero DOM da convertire in oggetto ParseException ParserXMLOrdine.parsingResult
Referenced by resources.ordine.xml.parserxml.ParserXMLOrdine.parseDocument.