resources::compositionlistapredefinitagusti::xml::generatorxml::GeneratorXMLCompositionListaPredefinitaGusti
Document resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.document
Rappresenta il documento "virtuale" sul quale andremo a creare il nostro albero DOM
Referenced by resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.createDOMTree, resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.get.
resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.GeneratorXMLCompositionListaPredefinitaGusti()
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe GeneratorXMLCompositionListaPredefinitaGusti.document
void resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.createDOMTree(ArrayList< CompositionListaPredefinitaGusti > data)
Crea l'albero DOM.
data Lista di oggetti da convertire in "nodi dell'albero DOM" ParserConfigurationException GeneratorXMLCompositionListaPredefinitaGusti.createDocument() GeneratorXMLCompositionListaPredefinitaGusti.document
References resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.createDocument, resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.document.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma2ActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro1ActionPerformed.
void resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.applyDOMonXMLFile(String filenameNpath)
Crea l'effettivo file XML sulla base dell'albero DOM.
filenameNpath Path del file XML di salvataggio TransformerConfigurationException TransformerException GeneratorXMLCompositionListaPredefinitaGusti.document
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma2ActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro1ActionPerformed.
void resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.createDocument()
Crea il documento "virtuale" supporto per il nostro albero DOM.
ParserConfigurationException GeneratorXMLCompositionListaPredefinitaGusti.document
Referenced by resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.createDOMTree.
Element resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.get(CompositionListaPredefinitaGusti singleElement)
Converte un oggetto in "nodo dell'albero DOM".
singleElement L'oggetto da convertire in "nodo dell'albero DOM" Il nodo dell'albero DOM (L'oggetto convertito in) GeneratorXMLCompositionListaPredefinitaGusti.document
References resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.document.