resources::ordine::xml::generatorxml::GeneratorXMLOrdine
Document resources.ordine.xml.generatorxml.GeneratorXMLOrdine.document
Rappresenta il documento "virtuale" sul quale andremo a creare il nostro albero DOM
Referenced by resources.ordine.xml.generatorxml.GeneratorXMLOrdine.createDOMTree, resources.ordine.xml.generatorxml.GeneratorXMLOrdine.get.
resources.ordine.xml.generatorxml.GeneratorXMLOrdine.GeneratorXMLOrdine()
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe GeneratorXMLOrdine.document
void resources.ordine.xml.generatorxml.GeneratorXMLOrdine.createDOMTree(ArrayList< Ordine > data)
Crea l'albero DOM.
data Lista di oggetti da convertire in "nodi dell'albero DOM" ParserConfigurationException GeneratorXMLOrdine.createDocument() GeneratorXMLOrdine.document
References resources.ordine.xml.generatorxml.GeneratorXMLOrdine.createDocument, resources.ordine.xml.generatorxml.GeneratorXMLOrdine.document.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorinoActionPerformed, resources.ordine.OrdineUpdater.run.
void resources.ordine.xml.generatorxml.GeneratorXMLOrdine.applyDOMonXMLFile(String filenameNpath)
Crea l'effettivo file XML sulla base dell'albero DOM.
filenameNpath Path del file XML di salvataggio TransformerConfigurationException TransformerException GeneratorXMLOrdine.document
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorinoActionPerformed, resources.ordine.OrdineUpdater.run.
void resources.ordine.xml.generatorxml.GeneratorXMLOrdine.createDocument()
Crea il documento "virtuale" supporto per il nostro albero DOM.
ParserConfigurationException GeneratorXMLOrdine.document
Referenced by resources.ordine.xml.generatorxml.GeneratorXMLOrdine.createDOMTree.
Element resources.ordine.xml.generatorxml.GeneratorXMLOrdine.get(Ordine singleElement)
Converte un oggetto in "nodo dell'albero DOM".
singleElement L'oggetto da convertire in "nodo dell'albero DOM" Il nodo dell'albero DOM (L'oggetto convertito in) GeneratorXMLOrdine.document
References resources.ordine.xml.generatorxml.GeneratorXMLOrdine.document.