guiGelataio::InterfacciaPrincipaleGalataio
final String guiGelataio.InterfacciaPrincipaleGalataio.pathLogo
Rappresenta la path di locazione dell'immagine utilizzata come logo della gelateria InterfacciaPrincipaleGalataio.logo
final ImageIcon guiGelataio.InterfacciaPrincipaleGalataio.logo
Rappresenta l'oggetto di classe ImageIcon utilizzato per inserire il logo all'interno di una label per permetterne la corretta visualizzazione sull'interfaccia InterfacciaPrincipaleGalataio.pathLogo
final DefaultListModel guiGelataio.InterfacciaPrincipaleGalataio.listaPredefinitaGustiModel
Rappresenta il modello lista della lista InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti
final DefaultListModel guiGelataio.InterfacciaPrincipaleGalataio.listaGustiVenditaModel
Rappresenta il modello lista della lista InterfacciaPrincipaleGalataio.jListListaGustiVendita InterfacciaPrincipaleGalataio.jListListaGustiVendita
final DefaultListModel guiGelataio.InterfacciaPrincipaleGalataio.listaGustiVenditaModelBackup
Rappresenta il modello lista backup della lista InterfacciaPrincipaleGalataio.jListListaGustiVendita InterfacciaPrincipaleGalataio.jListListaGustiVendita
final CurrentTime guiGelataio.InterfacciaPrincipaleGalataio.currentTime
Rappresenta l'oggetto di classe CurrentTime necessario per visualizzare correttamente l'orario corrente sull'interfaccia InterfacciaPrincipaleGalataio.timerCurrentTime InterfacciaPrincipaleGalataio.jLabelOraCorrente InterfacciaPrincipaleGalataio.jLabelOraCorrente1 InterfacciaPrincipaleGalataio.jLabelOraCorrente2 InterfacciaPrincipaleGalataio.jLabelOraCorrente3 InterfacciaPrincipaleGalataio.jLabelOraCorrente4 InterfacciaPrincipaleGalataio.jLabelOraCorrente5 resources.currenttime.CurrentTime
final Timer guiGelataio.InterfacciaPrincipaleGalataio.timerCurrentTime
Rappresenta l'oggetto di classe Timer necessario per l'aggiornamento continuo in background dell'ora corrente, per mantenerla "corrente" InterfacciaPrincipaleGalataio.currentTime InterfacciaPrincipaleGalataio.jLabelOraCorrente InterfacciaPrincipaleGalataio.jLabelOraCorrente1 InterfacciaPrincipaleGalataio.jLabelOraCorrente2 InterfacciaPrincipaleGalataio.jLabelOraCorrente3 InterfacciaPrincipaleGalataio.jLabelOraCorrente4 InterfacciaPrincipaleGalataio.jLabelOraCorrente5
final SpinnerNumberModel guiGelataio.InterfacciaPrincipaleGalataio.spinnerVaschettaPiccolaModel
Rappresenta il modello spinner dello spinner InterfacciaPrincipaleGalataio.jSpinnerVaschettaPiccola InterfacciaPrincipaleGalataio.jSpinnerVaschettaPiccola
final SpinnerNumberModel guiGelataio.InterfacciaPrincipaleGalataio.spinnerVaschettaMediaModel
Rappresenta il modello spinner dello spinner InterfacciaPrincipaleGalataio.jSpinnerVaschettaMedia InterfacciaPrincipaleGalataio.jSpinnerVaschettaMedia
final SpinnerNumberModel guiGelataio.InterfacciaPrincipaleGalataio.spinnerVaschettaGrandeModel
Rappresenta il modello spinner dello spinner InterfacciaPrincipaleGalataio.jSpinnerVaschettaGrande InterfacciaPrincipaleGalataio.jSpinnerVaschettaGrande
final JSpinner guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerVaschettaPiccolaBackup
Rappresenta lo spinner di backup dello spinner InterfacciaPrincipaleGalataio.jSpinnerVaschettaPiccola InterfacciaPrincipaleGalataio.jSpinnerVaschettaPiccola
final JSpinner guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerVaschettaMediaBackup
Rappresenta lo spinner di backup dello spinner InterfacciaPrincipaleGalataio.jSpinnerVaschettaMedia InterfacciaPrincipaleGalataio.jSpinnerVaschettaMedia
final JSpinner guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerVaschettaGrandeBackup
Rappresenta lo spinner di backup dello spinner InterfacciaPrincipaleGalataio.jSpinnerVaschettaGrande InterfacciaPrincipaleGalataio.jSpinnerVaschettaGrande
final SpinnerDateModel guiGelataio.InterfacciaPrincipaleGalataio.spinnerOraDiAperturaModel
Rappresenta il modello spinner dello spinner InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura
final SpinnerDateModel guiGelataio.InterfacciaPrincipaleGalataio.spinnerOraDiChiusuraModel
Rappresenta il modello spinner dello spinner InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura
final SpinnerDateModel guiGelataio.InterfacciaPrincipaleGalataio.spinnerOraDiAperturaBackupBlankModel
Rappresenta il modello spinner dello spinner InterfacciaPrincipaleGalataio.jSpinnerOraDiAperturaBackup InterfacciaPrincipaleGalataio.jSpinnerOraDiAperturaBackup
final SpinnerDateModel guiGelataio.InterfacciaPrincipaleGalataio.spinnerOraDiChiusuraBackupBlankModel
Rappresenta il modello spinner dello spinner InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusuraBackup InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusuraBackup
final JSpinner guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiAperturaBackup
Rappresenta lo spinner di backup dello spinner InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura
final JSpinner guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusuraBackup
Rappresenta lo spinner di backup dello spinner InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura
final Date guiGelataio.InterfacciaPrincipaleGalataio.currentDateAndTime
Rappresenta il vero e proprio orario aggiornato in modo automatico ("corrente") InterfacciaPrincipaleGalataio.currentTime InterfacciaPrincipaleGalataio.timerCurrentTime InterfacciaPrincipaleGalataio.jLabelOraCorrente InterfacciaPrincipaleGalataio.jLabelOraCorrente1 InterfacciaPrincipaleGalataio.jLabelOraCorrente2 InterfacciaPrincipaleGalataio.jLabelOraCorrente3 InterfacciaPrincipaleGalataio.jLabelOraCorrente4 InterfacciaPrincipaleGalataio.jLabelOraCorrente5
final ParserXMLModificaOrarioDelNegozio guiGelataio.InterfacciaPrincipaleGalataio.parserXMLModificaOrarioDelNegozio
Rappresenta il parser del file XML contenente la struttura "OrarioDelNegozio" InterfacciaPrincipaleGelataio.spinnerOraDiAperturaModel InterfacciaPrincipaleGelataio.spinnerOraDiChiusuraModel resources.orariodelnegozio.OrarioDelNegozio resources.orariodelnegozio.xml.parserxml.ParserXMLModificaOrarioDelNegozio
final GeneratorXMLModificaOrarioDelNegozio guiGelataio.InterfacciaPrincipaleGalataio.generatorXMLModificaOrarioDelNegozio
Rappresenta il generator del file XML contenente la struttura "OrarioDelNegozio" InterfacciaPrincipaleGelataio.spinnerOraDiAperturaModel InterfacciaPrincipaleGelataio.spinnerOraDiChiusuraModel resources.orariodelnegozio.OrarioDelNegozio resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio
final GeneratorXMLModificaPrezzoVaschette guiGelataio.InterfacciaPrincipaleGalataio.generatorXMLModificaPrezzoVaschette
Rappresenta il generator del file XML contenente la struttura "PrezzoVaschette" InterfacciaPrincipaleGelataio.spinnerVaschettaPiccolaModel InterfacciaPrincipaleGelataio.spinnerVaschettaMediaModel InterfacciaPrincipaleGelataio.spinnerVaschettaGrandeModel resources.prezzovaschette.PrezzoVaschette resources.prezzovaschette.xml.generatorxml.GeneratorXMLModificaPrezzoVaschette
final ParserXMLModificaPrezzoVaschette guiGelataio.InterfacciaPrincipaleGalataio.parserXMLModificaPrezzoVaschette
Rappresenta il parser del file XML contenente la struttura "PrezzoVaschette" InterfacciaPrincipaleGelataio.spinnerVaschettaPiccolaModel InterfacciaPrincipaleGelataio.spinnerVaschettaMediaModel InterfacciaPrincipaleGelataio.spinnerVaschettaGrandeModel resources.prezzovaschette.PrezzoVaschette resources.prezzovaschette.xml.parserxml.ParserXMLModificaPrezzoVaschette
final ParserXMLOrdine guiGelataio.InterfacciaPrincipaleGalataio.parserXMLOrdine
Rappresenta il parser del file XML contenente la struttura "Ordine" InterfacciaPrincipaleGalataio.jListListaGustiVendita resources.ordine.Ordine resources.ordine.xml.parserxml.ParserXMLOrdine
final GeneratorXMLOrdine guiGelataio.InterfacciaPrincipaleGalataio.generatorXMLOrdine
Rappresenta il generator del file XML contenente la struttura "Ordine" InterfacciaPrincipaleGalataio.jListListaGustiVendita resources.ordine.Ordine resources.ordine.xml.generatorxml.GeneratorXMLOrdine
final ParserXMLCompositionListaPredefinitaGusti guiGelataio.InterfacciaPrincipaleGalataio.parserXMLCompositionListaPredefinitaGusti
Rappresenta il parser del file XML contenente la struttura "CompositionListaPredefinitaGusti" InterfacciaPrincipaleGalataio.listaPredefinitaGustiModel resources.compositionlistapredefinitagusti.CompositionListaPredefinitaGusti resources.compositionlistapredefinitagusti.xml.parserxml.ParserXMLCompositionListaPredefinitaGusti
final GeneratorXMLCompositionListaPredefinitaGusti guiGelataio.InterfacciaPrincipaleGalataio.generatorXMLCompositionListaPredefinitaGusti
Rappresenta il generator del file XML contenente la struttura "CompositionListaPredefinitaGusti" InterfacciaPrincipaleGalataio.listaPredefinitaGustiModel resources.compositionlistapredefinitagusti.CompositionListaPredefinitaGusti resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti
final DefaultListModel guiGelataio.InterfacciaPrincipaleGalataio.listaOrdiniModel
Rappresenta il modello lista della lista InterfacciaPrincipaleGalataio.jListListaGustiVendita InterfacciaPrincipaleGalataio.jListListaGustiVendita
final OrdineUpdater guiGelataio.InterfacciaPrincipaleGalataio.ordineUpdater
Rappresenta l'oggetto di classe OrdineUpdater necessario per l'aggiornamento continuo in background degli ordini, automaticamente reperiti dal server InterfacciaPrincipaleGalataio.jListListaGustiVendita resources.ordine.OrdineUpdater
final Timer guiGelataio.InterfacciaPrincipaleGalataio.timerOrdineUpdater
Rappresenta l'oggetto di classe Timer necessario per l'aggiornamento continuo in background degli ordini, automaticamente reperiti dal server InterfacciaPrincipaleGalataio.jListListaGustiVendita resources.ordine.OrdineUpdater
final ListTextWrapper guiGelataio.InterfacciaPrincipaleGalataio.listTextWrapper
Rappresenta l'oggetto di classe ListTextWrapper per consentire una visualizzazione più ordinata degli ordini nella lista InterfacciaPrincipaleGalataio.jListListaGustiVendita InterfacciaPrincipaleGalataio.jListListaGustiVendita resources.listtextwrapper.ListTextWrapper
final FTPServer guiGelataio.InterfacciaPrincipaleGalataio.server
Rappresenta l'oggetto di classe FTPServer per permettere la comunicazione bidirezionale con il server FTP resources.ftpserver.FTPServer
final GeneratorXMLOrdinev2 guiGelataio.InterfacciaPrincipaleGalataio.generatorXMLOrdinev2
Rappresenta il generator v2 del file XML contenente la struttura "Ordine" InterfacciaPrincipaleGalataio.jListListaGustiVendita resources.ordine.Ordine resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2
GeneratorXMLOrdinev3 guiGelataio.InterfacciaPrincipaleGalataio.generatorXMLOrdinev3
Rappresenta il generator v3 del file XML contenente la struttura "Ordine" InterfacciaPrincipaleGalataio.jListListaGustiVendita resources.ordine.Ordine resources.ordine.xml.generatorxmlv3.GeneratorXMLOrdinev3
ArrayList<Ordine> guiGelataio.InterfacciaPrincipaleGalataio.resultOrdiniNonEvasi
Rappresenta la lista per la gestione degli ordini non evasi InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio() InterfacciaPrincipaleGalataio.loadFromServer()
final ArrayList<CompositionListaPredefinitaGusti> guiGelataio.InterfacciaPrincipaleGalataio.flusher
Rappresenta una lista utilizzata a scopo di rollback di modifiche da annullare InterfacciaPrincipaleGalataio.jButtonIndietro1ActionPerformed() InterfacciaPrincipaleGalataio.jButtonRimuoviActionPerformed() InterfacciaPrincipaleGalataio.jButtonModificaListaPredefinitaGustiActionPerformed()
final CronologyUpdater guiGelataio.InterfacciaPrincipaleGalataio.cronologyUpdater
Rappresenta l'oggetto di classe CronologyUpdater necessario per l'aggiornamento continuo del valore del conteggio di frammenti cronologici degli ordini evasi in background resources.cronology.CronologyUpdater
final Timer guiGelataio.InterfacciaPrincipaleGalataio.timerCronologyUpdater
Rappresenta l'oggetto di classe Timer necessario per l'aggiornamento continuo del valore del conteggio di frammenti cronologici degli ordini evasi in background InterfacciaPrincipaleGalataio.cronologyUpdater
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonAggiungi
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonAnnulla
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonAnnulla2
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma2
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonEliminaCronologiaOrdinazioni
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonImpostazioni
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro1
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorino
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonInserisci
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaListaGustiInVendita
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaListaPredefinitaGusti
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaOrarioNegozio
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonRimuovi
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonRimuovi1
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JButton guiGelataio.InterfacciaPrincipaleGalataio.jButtonScaricaCronologiaOrdinazioni
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JComboBox<String> guiGelataio.InterfacciaPrincipaleGalataio.jComboBoxTipo
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelFrammentiCronologici
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelListaGustiVendita
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelListaPredefinitaGusti
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelListaPredefinitaGusti1
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo1
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo2
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo3
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo5
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente1
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente2
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente3
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente5
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraDiApertura
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraDiChiusura
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JLabel guiGelataio.InterfacciaPrincipaleGalataio.jLabelOrdini
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JList<String> guiGelataio.InterfacciaPrincipaleGalataio.jListListaGustiVendita
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JList<String> guiGelataio.InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio, guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JList<String> guiGelataio.InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti1
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JList<String> guiGelataio.InterfacciaPrincipaleGalataio.jListOrdini
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JPanel guiGelataio.InterfacciaPrincipaleGalataio.jPanelImpostazioni
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JPanel guiGelataio.InterfacciaPrincipaleGalataio.jPanelInterfacciaPrincipaleGelataio
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JPanel guiGelataio.InterfacciaPrincipaleGalataio.jPanelMenu
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JPanel guiGelataio.InterfacciaPrincipaleGalataio.jPanelModificaListaGustiInVendita
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JPanel guiGelataio.InterfacciaPrincipaleGalataio.jPanelModificaListaPredefinita
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JPanel guiGelataio.InterfacciaPrincipaleGalataio.jPanelModificaOrarioNegozio
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JScrollPane guiGelataio.InterfacciaPrincipaleGalataio.jScrollPane
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JScrollPane guiGelataio.InterfacciaPrincipaleGalataio.jScrollPane1
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JScrollPane guiGelataio.InterfacciaPrincipaleGalataio.jScrollPane2
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JScrollPane guiGelataio.InterfacciaPrincipaleGalataio.jScrollPane3
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JSpinner guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JSpinner guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JSpinner guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerPrezzo
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JTabbedPane guiGelataio.InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JTabbedPane guiGelataio.InterfacciaPrincipaleGalataio.jTabbedPaneMain
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState, guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
javax.swing.JTextField guiGelataio.InterfacciaPrincipaleGalataio.jTextFieldGustoListaPredefinita
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.initComponents.
guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio()
Costruttore.
Creates new form InterfacciaPrincipaleGalataio Inizializza tutte le risorse necessarie ad un oggetto di questa classe InterfacciaPrincipaleGalataio.pathLogo InterfacciaPrincipaleGalataio.logo InterfacciaPrincipaleGalataio.listaPredefinitaGustiModel InterfacciaPrincipaleGalataio.listaGustiVenditaModel InterfacciaPrincipaleGalataio.listaGustiVenditaModelBackup InterfacciaPrincipaleGalataio.currentTime InterfacciaPrincipaleGalataio.timerCurrentTime InterfacciaPrincipaleGalataio.spinnerVaschettaPiccolaModel InterfacciaPrincipaleGalataio.spinnerVaschettaMediaModel InterfacciaPrincipaleGalataio.spinnerVaschettaGrandeModel InterfacciaPrincipaleGalataio.jSpinnerVaschettaPiccolaBackup InterfacciaPrincipaleGalataio.jSpinnerVaschettaMediaBackup InterfacciaPrincipaleGalataio.jSpinnerVaschettaGrandeBackup InterfacciaPrincipaleGalataio.currentDateAndTime InterfacciaPrincipaleGalataio.spinnerOraDiAperturaModel InterfacciaPrincipaleGalataio.spinnerOraDiChiusuraModel InterfacciaPrincipaleGalataio.spinnerOraDiAperturaBackupBlankModel InterfacciaPrincipaleGalataio.spinnerOraDiChiusuraBackupBlankModel InterfacciaPrincipaleGalataio.jSpinnerOraDiAperturaBackup InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusuraBackup InterfacciaPrincipaleGalataio.parserXMLModificaOrarioDelNegozio InterfacciaPrincipaleGalataio.generatorXMLModificaOrarioDelNegozio InterfacciaPrincipaleGalataio.parserXMLModificaPrezzoVaschette InterfacciaPrincipaleGalataio.generatorXMLModificaPrezzoVaschette InterfacciaPrincipaleGalataio.parserXMLOrdine InterfacciaPrincipaleGalataio.generatorXMLOrdine InterfacciaPrincipaleGalataio.parserXMLCompositionListaPredefinitaGusti InterfacciaPrincipaleGalataio.generatorXMLCompositionListaPredefinitaGusti InterfacciaPrincipaleGalataio.listaOrdiniModel InterfacciaPrincipaleGalataio.server InterfacciaPrincipaleGalataio.ordineUpdater InterfacciaPrincipaleGalataio.timerOrdineUpdater InterfacciaPrincipaleGalataio.listTextWrapper InterfacciaPrincipaleGalataio.generatorXMLOrdinev2 InterfacciaPrincipaleGalataio.generatorXMLOrdinev3 InterfacciaPrincipaleGalataio.ordineUpdaterv2 InterfacciaPrincipaleGalataio.initComponents() InterfacciaPrincipaleGalataio.stableState() InterfacciaPrincipaleGalataio.cronologyUpdater InterfacciaPrincipaleGalataio.timerCronologyUpdater
References guiGelataio.InterfacciaPrincipaleGalataio.initComponents, guiGelataio.InterfacciaPrincipaleGalataio.jLabelFrammentiCronologici, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente1, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente2, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente3, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente5, guiGelataio.InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti, guiGelataio.InterfacciaPrincipaleGalataio.stableState.
void guiGelataio.InterfacciaPrincipaleGalataio.stableState()
Inizializzatore stabile.
Stabilisce una connessione con il server FTP e gestisce eventuali errori di connessione. Recupera informazioni necessarie ad inizializzare le necessarie risorse per il corretto funzionamento del software dal server e gestisce eventuali errori di recupero delle informazioni. Assegna valori stabili alle risorse che necessitano di un valore forzato per il corretto funzionamento. InterfacciaPrincipaleGalataio.server InterfacciaPrincipaleGalataio.timerCurrentTime InterfacciaPrincipaleGalataio.timerOrdineUpdater InterfacciaPrincipaleGalataio.jLabelLogo InterfacciaPrincipaleGalataio.jLabelLogo1 InterfacciaPrincipaleGalataio.jLabelLogo2 InterfacciaPrincipaleGalataio.jLabelLogo3 InterfacciaPrincipaleGalataio.jLabelLogo4 InterfacciaPrincipaleGalataio.jLabelLogo5 InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti1 InterfacciaPrincipaleGalataio.jListListaGustiVendita InterfacciaPrincipaleGalataio.jListOrdini InterfacciaPrincipaleGalataio.spinnerVaschettaPiccolaModel InterfacciaPrincipaleGalataio.spinnerVaschettaMediaModel InterfacciaPrincipaleGalataio.spinnerVaschettaGrandeModel InterfacciaPrincipaleGalataio.jTabbedPaneMain InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni InterfacciaPrincipaleGalataio.spinnerValueCopy() InterfacciaPrincipaleGalataio.loadFromServer() InterfacciaPrincipaleGalataio.cronologyUpdater InterfacciaPrincipaleGalataio.timerCronologyUpdater
References resources.ftpserver.FTPServer.connect, guiGelataio.InterfacciaPrincipaleGalataio.defaultListModelCopy, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo1, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo2, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo3, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo5, guiGelataio.InterfacciaPrincipaleGalataio.jListListaGustiVendita, guiGelataio.InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti, guiGelataio.InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti1, guiGelataio.InterfacciaPrincipaleGalataio.jListOrdini, guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura, guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura, guiGelataio.InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni, guiGelataio.InterfacciaPrincipaleGalataio.jTabbedPaneMain, guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer, resources.ftpserver.FTPServer.login, resources.ftpserver.FTPServer.setCoords, guiGelataio.InterfacciaPrincipaleGalataio.spinnerValueCopy.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio.
void guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer()
Recupera informazioni necessarie dal server.
Recupera informazioni necessarie ad inizializzare le necessarie risorse per il corretto funzionamento del software dal server e gestisce eventuali errori di recupero delle informazioni. La connessione con il server FTP deve essere già stata stabilita InterfacciaPrincipaleGalataio.server InterfacciaPrincipaleGalataio.spinnerOraDiAperturaModel InterfacciaPrincipaleGalataio.spinnerOraDiChiusuraModel InterfacciaPrincipaleGalataio.spinnerVaschettaPiccolaModel InterfacciaPrincipaleGalataio.spinnerVaschettaMediaModel InterfacciaPrincipaleGalataio.spinnerVaschettaGrandeModel InterfacciaPrincipaleGalataio.listaPredefinitaGustiModel InterfacciaPrincipaleGalataio.listaGustiVenditaModel InterfacciaPrincipaleGalataio.jSpinnerOraDiAperturaBackup InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusuraBackup InterfacciaPrincipaleGalataio.listaOrdiniModel InterfacciaPrincipaleGalataio.parserXMLModificaOrarioDelNegozio InterfacciaPrincipaleGalataio.parserXMLModificaPrezzoVaschette InterfacciaPrincipaleGalataio.parserXMLCompositionListaPredefinitaGusti InterfacciaPrincipaleGalataio.parserXMLOrdine
References resources.ftpserver.FTPServer.downloadFile, resources.orariodelnegozio.OrarioDelNegozio.getOraDiAperturaDate, resources.orariodelnegozio.OrarioDelNegozio.getOraDiChiusuraDate, resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaGrande, resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaMedia, resources.prezzovaschette.PrezzoVaschette.getPrezzoVaschettaPiccola, guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura, guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura, guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerPrezzo, resources.prezzovaschette.xml.parserxml.ParserXMLModificaPrezzoVaschette.parseDocument, resources.orariodelnegozio.xml.parserxml.ParserXMLModificaOrarioDelNegozio.parseDocument, resources.compositionlistapredefinitagusti.xml.parserxml.ParserXMLCompositionListaPredefinitaGusti.parseDocument, resources.ordine.xml.parserxml.ParserXMLOrdine.parseDocument, resources.ftpserver.FTPServer.setCurrentDirectory.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState.
void guiGelataio.InterfacciaPrincipaleGalataio.initComponents()
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
References guiGelataio.InterfacciaPrincipaleGalataio.jButtonAggiungi, guiGelataio.InterfacciaPrincipaleGalataio.jButtonAnnulla, guiGelataio.InterfacciaPrincipaleGalataio.jButtonAnnulla2, guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma, guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma2, guiGelataio.InterfacciaPrincipaleGalataio.jButtonEliminaCronologiaOrdinazioni, guiGelataio.InterfacciaPrincipaleGalataio.jButtonImpostazioni, guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro, guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro1, guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorino, guiGelataio.InterfacciaPrincipaleGalataio.jButtonInserisci, guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaListaGustiInVendita, guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaListaPredefinitaGusti, guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaOrarioNegozio, guiGelataio.InterfacciaPrincipaleGalataio.jButtonRimuovi, guiGelataio.InterfacciaPrincipaleGalataio.jButtonRimuovi1, guiGelataio.InterfacciaPrincipaleGalataio.jButtonScaricaCronologiaOrdinazioni, guiGelataio.InterfacciaPrincipaleGalataio.jComboBoxTipo, guiGelataio.InterfacciaPrincipaleGalataio.jLabelFrammentiCronologici, guiGelataio.InterfacciaPrincipaleGalataio.jLabelListaGustiVendita, guiGelataio.InterfacciaPrincipaleGalataio.jLabelListaPredefinitaGusti, guiGelataio.InterfacciaPrincipaleGalataio.jLabelListaPredefinitaGusti1, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo1, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo2, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo3, guiGelataio.InterfacciaPrincipaleGalataio.jLabelLogo5, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente1, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente2, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente3, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraCorrente5, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraDiApertura, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOraDiChiusura, guiGelataio.InterfacciaPrincipaleGalataio.jLabelOrdini, guiGelataio.InterfacciaPrincipaleGalataio.jListListaGustiVendita, guiGelataio.InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti, guiGelataio.InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti1, guiGelataio.InterfacciaPrincipaleGalataio.jListOrdini, guiGelataio.InterfacciaPrincipaleGalataio.jPanelImpostazioni, guiGelataio.InterfacciaPrincipaleGalataio.jPanelInterfacciaPrincipaleGelataio, guiGelataio.InterfacciaPrincipaleGalataio.jPanelMenu, guiGelataio.InterfacciaPrincipaleGalataio.jPanelModificaListaGustiInVendita, guiGelataio.InterfacciaPrincipaleGalataio.jPanelModificaListaPredefinita, guiGelataio.InterfacciaPrincipaleGalataio.jPanelModificaOrarioNegozio, guiGelataio.InterfacciaPrincipaleGalataio.jScrollPane, guiGelataio.InterfacciaPrincipaleGalataio.jScrollPane1, guiGelataio.InterfacciaPrincipaleGalataio.jScrollPane2, guiGelataio.InterfacciaPrincipaleGalataio.jScrollPane3, guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura, guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura, guiGelataio.InterfacciaPrincipaleGalataio.jSpinnerPrezzo, guiGelataio.InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni, guiGelataio.InterfacciaPrincipaleGalataio.jTabbedPaneMain, guiGelataio.InterfacciaPrincipaleGalataio.jTextFieldGustoListaPredefinita.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.InterfacciaPrincipaleGalataio.
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonAnnulla2ActionPerformed(java.awt.event.ActionEvent evt)
Bottone annulla dell'interfaccia "Modifica Lista Gusti In Vendita".
Il metodo viene richiamato alla pressione del bottone annulla dell'interfaccia "Modifica Lista Gusti In Vendita" e annulla tutte le modifiche effettuate ripristinando l'ultimo stato stabile. Infine, ritorna all'interfaccia "Main". evt Evento InterfacciaPrincipaleGalataio.defaultListModelCopy() InterfacciaPrincipaleGalataio.jTabbedPaneMain
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma2ActionPerformed(java.awt.event.ActionEvent evt)
Bottone conferma dell'interfaccia "Modifica Lista Gusti In Vendita".
Il metodo viene richiamato alla pressione del bottone conferma dell'interfaccia "Modifica Lista Gusti In Vendita" e salva tutte le modifiche effettuate, definendo di conseguenza l'ultimo stato stabile. Effettua successivamente il caricamento dei nuovi parametri nel server, gestendo eventuali errori di comunicazione. Infine, ritorna all'interfaccia "Main". evt Evento InterfacciaPrincipaleGalataio.defaultListModelCopy() InterfacciaPrincipaleGalataio.listaGustiVenditaModel InterfacciaPrincipaleGalataio.generatorXMLCompositionListaPredefinitaGusti InterfacciaPrincipaleGalataio.server InterfacciaPrincipaleGalataio.jTabbedPaneMain
References resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.applyDOMonXMLFile, resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.createDOMTree, resources.ftpserver.FTPServer.setCurrentDirectory, resources.ftpserver.FTPServer.uploadFile.
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonRimuovi1ActionPerformed(java.awt.event.ActionEvent evt)
Bottone rimuovi dell'interfaccia "Modifica Lista Gusti In Vendita".
Il metodo viene richiamato alla pressione del bottone rimuovi dell'interfaccia "Modifica Lista Gusti In Vendita" e rimuove l'elemento selezionato nella lista InterfacciaPrincipaleGalataio.jListListaGustiVendita e gestisce eventuali errori durante la rimozione. evt Evento L'elemento da rimuovere deve essere già stato selezionato InterfacciaPrincipaleGalataio.jListListaGustiVendita InterfacciaPrincipaleGalataio.listaGustiVenditaModel
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonInserisciActionPerformed(java.awt.event.ActionEvent evt)
Bottone inserisci dell'interfaccia "Modifica Lista Gusti In Vendita".
Il metodo viene richiamato alla pressione del bottone inserisci dell'interfaccia "Modifica Lista Gusti In Vendita" e aggiunge un nuovo elemento nella lista InterfacciaPrincipaleGalataio.jListListaGustiVendita e gestisce eventuali errori durante l'aggiunta. L'elemento da aggiungere viene selezionato dalla lista InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti1. evt Evento L'elemento da aggiungere deve essere già stato selezionato InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti1 InterfacciaPrincipaleGalataio.listaGustiVenditaModel
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonImpostazioniActionPerformed(java.awt.event.ActionEvent evt)
Bottone impostazioni dell'interfaccia "Main".
Il metodo viene richiamato alla pressione del bottone impostazioni dell'interfaccia "Main" e apre l'interfaccia "Impostazioni". evt Evento InterfacciaPrincipaleGalataio.jTabbedPaneMain InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaListaGustiInVenditaActionPerformed(java.awt.event.ActionEvent evt)
Bottone modifica lista gusti in vendita dell'interfaccia "Main".
Il metodo viene richiamato alla pressione del bottone modifica lista gusti in vendita dell'interfaccia "Main" e apre l'interfaccia "Modifica Lista Gusti In Vendita". evt Evento InterfacciaPrincipaleGalataio.jTabbedPaneMain
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorinoActionPerformed(java.awt.event.ActionEvent evt)
Bottone inoltro al fattorino dell'interfaccia "Main".
Il metodo viene richiamato alla pressione del bottone inoltro al fattorino dell'interfaccia "Main" ed effettua l'inoltro dell'ordinazione selezionata dalla lista InterfacciaPrincipaleGalataio.jListOrdini al fattorino e gestisce eventuli errori durante l'inoltro. evt Evento L'ordine da inoltrare deve essere già stato selezionato InterfacciaPrincipaleGalataio.jListOrdini InterfacciaPrincipaleGalataio.listaOrdiniModel InterfacciaPrincipaleGalataio.generatorXMLOrdinev2 InterfacciaPrincipaleGalataio.server InterfacciaPrincipaleGalataio.generatorXMLOrdine
References resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.applyDOMonXMLFile, resources.ordine.xml.generatorxml.GeneratorXMLOrdine.applyDOMonXMLFile, resources.ordine.xml.generatorxml.GeneratorXMLOrdine.createDOMTree, resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.createDOMTree, resources.ftpserver.FTPServer.setCurrentDirectory, resources.ftpserver.FTPServer.uploadFile, resources.ftpserver.FTPServer.uploadUniqueFile.
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonAnnullaActionPerformed(java.awt.event.ActionEvent evt)
Bottone annulla dell'interfaccia "Modifica Orario Negozio".
Il metodo viene richiamato alla pressione del bottone annulla dell'interfaccia "Modifica Orario Negozio" e annulla tutte le modifiche effettuate ripristinando l'ultimo stato stabile. Infine, ritorna all'interfaccia "Menù". evt Evento InterfacciaPrincipaleGalataio.spinnerValueCopy() InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonConfermaActionPerformed(java.awt.event.ActionEvent evt)
Bottone conferma dell'interfaccia "Modifica Orario Negozio".
Il metodo viene richiamato alla pressione del bottone conferma dell'interfaccia "Modifica Orario Negozio" e salva tutte le modifiche effettuate, definendo di conseguenza l'ultimo stato stabile. Effettua successivamente il caricamento dei nuovi parametri nel server, gestendo eventuali errori di comunicazione. Infine, ritorna all'interfaccia "Menù". evt Evento InterfacciaPrincipaleGalataio.jSpinnerOraDiApertura InterfacciaPrincipaleGalataio.jSpinnerOraDiChiusura InterfacciaPrincipaleGalataio.spinnerValueCopy() InterfacciaPrincipaleGalataio.generatorXMLModificaOrarioDelNegozio InterfacciaPrincipaleGalataio.server InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni
References resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.applyDOMonXMLFile, resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.createDOMTree, resources.ftpserver.FTPServer.setCurrentDirectory, resources.ftpserver.FTPServer.uploadFile.
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro1ActionPerformed(java.awt.event.ActionEvent evt)
Bottone indietro dell'interfaccia "Modifica Lista Predefinita".
Il metodo viene richiamato alla pressione del bottone indietro dell'interfaccia "Modifica Lista Predefinita" e salva tutte le modifiche effettuate, definendo di conseguenza l'ultimo stato stabile. Effettua successivamente il caricamento dei nuovi parametri nel server, gestendo eventuali errori di comunicazione. Infine, ritorna all'interfaccia "Menù". evt Evento InterfacciaPrincipaleGalataio.generatorXMLCompositionListaPredefinitaGusti InterfacciaPrincipaleGalataio.server InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni
References resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.applyDOMonXMLFile, resources.compositionlistapredefinitagusti.xml.generatorxml.GeneratorXMLCompositionListaPredefinitaGusti.createDOMTree, resources.ftpserver.FTPServer.setCurrentDirectory, resources.ftpserver.FTPServer.uploadFile.
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonRimuoviActionPerformed(java.awt.event.ActionEvent evt)
Bottone rimuovi dell'interfaccia "Modifica Lista Predefinita".
Il metodo viene richiamato alla pressione del bottone rimuovi dell'interfaccia "Modifica Lista Predefinita" e rimuove l'elemento selezionato nella lista InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti e gestisce eventuali errori durante la rimozione. evt Evento L'elemento da rimuovere deve essere già stato selezionato InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti InterfacciaPrincipaleGalataio.listaPredefinitaGustiModel InterfacciaPrincipaleGalataio.defaultListModelCopy()
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonAggiungiActionPerformed(java.awt.event.ActionEvent evt)
Bottone aggiungi dell'interfaccia "Modifica Lista Predefinita".
Il metodo viene richiamato alla pressione del bottone aggiungi dell'interfaccia "Modifica Lista Predefinita" e aggiunge un nuovo elemento nella lista InterfacciaPrincipaleGalataio.jListListaPredefinitaGusti con valore letterale specificato in InterfacciaPrincipaleGalataio.jTextFieldGustoListaPredefinita e gestisce eventuali errori durante l'aggiunta. evt Evento InterfacciaPrincipaleGalataio.jTextFieldGustoListaPredefinita deve contenere un valore testuale valido InterfacciaPrincipaleGalataio.jTextFieldGustoListaPredefinita InterfacciaPrincipaleGalataio.listaPredefinitaGustiModel
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietroActionPerformed(java.awt.event.ActionEvent evt)
Bottone indietro dell'interfaccia "Menù".
Il metodo viene richiamato alla pressione del bottone indietro dell'interfaccia "Menù" e ritorna all'interfaccia "Main". evt Evento InterfacciaPrincipaleGalataio.jTabbedPaneMain InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaOrarioNegozioActionPerformed(java.awt.event.ActionEvent evt)
Bottone modifica orario negozio dell'interfaccia "Menù".
Il metodo viene richiamato alla pressione del bottone modifica orario negozio dell'interfaccia "Menù" e apre l'interfaccia "Modifica Orario Negozio". evt Evento InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonModificaListaPredefinitaGustiActionPerformed(java.awt.event.ActionEvent evt)
Bottone modifica lista predefinita gusti dell'interfaccia "Menù".
Il metodo viene richiamato alla pressione del bottone modifica lista predefinita gusti dell'interfaccia "Menù" e apre l'interfaccia "Modifica Lista Predefinita". evt Evento InterfacciaPrincipaleGalataio.jTabbedPaneImpostazioni
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonScaricaCronologiaOrdinazioniActionPerformed(java.awt.event.ActionEvent evt)
References resources.ordine.xml.generatorxmlv3.GeneratorXMLOrdinev3.applyDOMonXMLFile, resources.ordine.xml.generatorxmlv3.GeneratorXMLOrdinev3.createDOMTree, resources.ftpserver.FTPServer.downloadFile, resources.ftpserver.FTPServer.getListElements, resources.ordine.xml.parserxml.ParserXMLOrdine.parseDocument, resources.ftpserver.FTPServer.setCurrentDirectory.
void guiGelataio.InterfacciaPrincipaleGalataio.jButtonEliminaCronologiaOrdinazioniActionPerformed(java.awt.event.ActionEvent evt)
References resources.ftpserver.FTPServer.deleteFile, resources.ftpserver.FTPServer.getListElements, resources.ftpserver.FTPServer.setCurrentDirectory.
static void guiGelataio.InterfacciaPrincipaleGalataio.spinnerValueCopy(JSpinner src, JSpinner dest)
Copia il valore contenuto nello spinner src nello spinner dest.
src Lo spinner dal quale prelevare il valore da copiare dest Lo spinner nel quale copiare il valore da copiare
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState.
static void guiGelataio.InterfacciaPrincipaleGalataio.defaultListModelCopy(DefaultListModel src, DefaultListModel dest)
Copia il valore dal modello lista src nel modello lista dest.
src Il modello lista dal quale prelevare il valore da copiare dest Il modello lista nel quale copiare il valore da copiare
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState.
static void guiGelataio.InterfacciaPrincipaleGalataio.main(String args[])
args the command line arguments