resources::ftpserver::Manager
final FTPClient resources.ftpserver.Manager.server
Rappresenta un oggetto di classe FTPClient, la quale fornisce vari servizi per la comunicazione con un server FTP
Referenced by resources.ftpserver.Manager.getServer.
final Semaphore resources.ftpserver.Manager.serverMutex
Rappresenta un oggetto di classe Semaphore per gestire la concorrenza nell'accesso alla risorsa Manager.server
Referenced by resources.ftpserver.Manager.getServerMutex.
Boolean resources.ftpserver.Manager.isConnected
Rappresenta un flag booleano indicante se o se non si è connessi al server
Referenced by resources.ftpserver.Manager.getIsConnected, resources.ftpserver.Manager.setIsConnected.
final Boolean resources.ftpserver.Manager.showServerReplies
Rappresenta un flag booleano indicante se o se non visualizzare le risposte del server su console
Referenced by resources.ftpserver.Manager.Manager, resources.ftpserver.Manager.getShowServerReplies.
final Boolean resources.ftpserver.Manager.isNoOp
Rappresenta un flag booleano indicante se o se non il server supporta la funzione keep alive tramite comandi "noop"
Referenced by resources.ftpserver.Manager.Manager, resources.ftpserver.Manager.getIsNoOp.
final Boolean resources.ftpserver.Manager.isLogBidirectional
Rappresenta un flag booleano indicante se o se non il server supporta il logout con possibile login successivo senza disconnessione
Referenced by resources.ftpserver.Manager.Manager, resources.ftpserver.Manager.getIsLogBidirectional.
resources.ftpserver.Manager.Manager(final Boolean showServerReplies, final Boolean isNoOp, final Boolean isLogBidirectional)
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe showServerReplies Flag booleano indicante se o se non visualizzare le risposte del server su console isNoOp Flag booleano indicante se o se non il server supporta la funzione keep alive tramite comandi "noop" isLogBidirectional Flag booleano indicante se o se non il server supporta il logout con possibile login successivo senza disconnessione Manager.server Manager.serverMutex Manager.isConnected Manager.showServerReplies Manager.isNoOp Manager.isLogBidirectional
References resources.ftpserver.Manager.isLogBidirectional, resources.ftpserver.Manager.isNoOp, resources.ftpserver.Manager.showServerReplies.
FTPClient resources.ftpserver.Manager.getServer()
Ritorna il valore dell'attributo Manager.server.
Il valore dell'attributo Manager.server Manager.server
References resources.ftpserver.Manager.server.
Referenced by resources.ftpserver.FTPServer.connect, resources.ftpserver.FTPServer.connectAM, resources.ftpserver.FTPServer.deleteFile, resources.ftpserver.FTPServer.deleteFileAM, resources.ftpserver.FTPServer.disconnect, resources.ftpserver.FTPServer.disconnectAM, resources.ftpserver.FTPServer.downloadFile, resources.ftpserver.FTPServer.downloadFileAM, resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.FTPServer.getCurrentDirectory, resources.ftpserver.FTPServer.getCurrentDirectoryAM, resources.ftpserver.FTPServer.getListElements, resources.ftpserver.FTPServer.getListElementsAM, resources.ftpserver.FTPServer.getServerBackdoor, resources.ftpserver.FTPServer.login, resources.ftpserver.FTPServer.loginAM, resources.ftpserver.FTPServer.logout, resources.ftpserver.FTPServer.logoutAM, resources.ftpserver.Keeper.run, resources.ftpserver.FTPServer.setCurrentDirectory, resources.ftpserver.FTPServer.setCurrentDirectoryAM, resources.ftpserver.FTPServer.uploadFile, resources.ftpserver.FTPServer.uploadFileAM, resources.ftpserver.FTPServer.uploadUniqueFile, resources.ftpserver.FTPServer.uploadUniqueFileAM.
Semaphore resources.ftpserver.Manager.getServerMutex()
Ritorna il valore dell'attributo Manager.serverMutex.
Il valore dell'attributo Manager.serverMutex Manager.serverMutex
References resources.ftpserver.Manager.serverMutex.
Referenced by resources.ftpserver.FTPServer.connect, resources.ftpserver.FTPServer.connectAM, resources.ftpserver.FTPServer.deleteFile, resources.ftpserver.FTPServer.deleteFileAM, resources.ftpserver.FTPServer.disconnect, resources.ftpserver.FTPServer.disconnectAM, resources.ftpserver.FTPServer.downloadFile, resources.ftpserver.FTPServer.downloadFileAM, resources.ftpserver.FTPServer.getCurrentDirectory, resources.ftpserver.FTPServer.getCurrentDirectoryAM, resources.ftpserver.FTPServer.getListElements, resources.ftpserver.FTPServer.getListElementsAM, resources.ftpserver.FTPServer.login, resources.ftpserver.FTPServer.loginAM, resources.ftpserver.FTPServer.logout, resources.ftpserver.FTPServer.logoutAM, resources.ftpserver.Keeper.run, resources.ftpserver.FTPServer.setCurrentDirectory, resources.ftpserver.FTPServer.setCurrentDirectoryAM, resources.ftpserver.FTPServer.uploadFile, resources.ftpserver.FTPServer.uploadFileAM, resources.ftpserver.FTPServer.uploadUniqueFile, resources.ftpserver.FTPServer.uploadUniqueFileAM.
Boolean resources.ftpserver.Manager.getIsConnected()
Ritorna il valore dell'attributo Manager.isConnected.
Il valore dell'attributo Manager.isConnected Manager.isConnected
References resources.ftpserver.Manager.isConnected.
Referenced by resources.ftpserver.FTPServer.connect, resources.ftpserver.FTPServer.connectAM, resources.ftpserver.FTPServer.disconnect, resources.ftpserver.FTPServer.disconnectAM, resources.ftpserver.FTPServer.getCurrentDirectory, resources.ftpserver.FTPServer.getIsConnected, resources.ftpserver.FTPServer.login, resources.ftpserver.FTPServer.loginAM, resources.ftpserver.Keeper.run, resources.ftpserver.FTPServer.setCoords, resources.ftpserver.FTPServer.setCoordsAM.
void resources.ftpserver.Manager.setIsConnected(Boolean isConnected)
Imposta il valore dell'attributo Manager.isConnected.
isConnected Il valore da assegnare all'attributo Manager.isConnected Manager.isConnected
References resources.ftpserver.Manager.isConnected.
Referenced by resources.ftpserver.FTPServer.connect, resources.ftpserver.FTPServer.connectAM, resources.ftpserver.FTPServer.disconnect, resources.ftpserver.FTPServer.disconnectAM.
Boolean resources.ftpserver.Manager.getIsNoOp()
Ritorna il valore dell'attributo Manager.isNoOp.
Il valore dell'attributo Manager.isNoOp Manager.isNoOp
References resources.ftpserver.Manager.isNoOp.
Referenced by resources.ftpserver.FTPServer.getIsNoOp, resources.ftpserver.Keeper.run.
Boolean resources.ftpserver.Manager.getShowServerReplies()
Ritorna il valore dell'attributo Manager.showServerReplies.
Il valore dell'attributo Manager.showServerReplies Manager.showServerReplies
References resources.ftpserver.Manager.showServerReplies.
Referenced by resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.FTPServer.getShowServerReplies, resources.ftpserver.Keeper.run.
Boolean resources.ftpserver.Manager.getIsLogBidirectional()
Ritorna il valore dell'attributo Manager.isLogBidirectional.
Il valore dell'attributo Manager.isLogBidirectional Manager.isLogBidirectional
References resources.ftpserver.Manager.isLogBidirectional.
Referenced by resources.ftpserver.FTPServer.logout, resources.ftpserver.FTPServer.logoutAM.