resources::ftpserver::FTPServer
final Manager resources.ftpserver.FTPServer.manager
Rappresenta un oggetto di classe resources.ftpserver.Manager, classe contenente dati condivisi tra le classi resources.ftpserver.FTPServer e resources.ftpserver.Keeper resources.ftpserver.FTPServer resources.ftpserver.Manager resources.ftpserver.Keeper
Referenced by resources.ftpserver.FTPServer.FTPServer.
final Keeper resources.ftpserver.FTPServer.keeper
Rappresenta un oggetto di classe resources.ftpserver.Keeper, il quale rappresenta un thread daemon per mantenere attiva la comunicazione client-server, anche in stato di idle resources.ftpserver.Keeper
Referenced by resources.ftpserver.FTPServer.startKeeper.
final Timer resources.ftpserver.FTPServer.timer
Rappresenta un oggetto di classe Timer, il quale è necessario per garantire la corretta esecuzione schedulata del thread FTPServer.keeper FTPServer.keeper
String [] resources.ftpserver.FTPServer.backupReplies
Rappresenta una variabile di backup utilizzata per implementare la protezione contro messaggi duplicati di risposta da parte del server FTPServer.getAndPrintServerReply()
String resources.ftpserver.FTPServer.host
Rappresenta la prima coordinata per la comunicazione con il server FTP: host
Referenced by resources.ftpserver.FTPServer.setCoords, resources.ftpserver.FTPServer.setCoordsAM, resources.ftpserver.FTPServer.getHost.
Integer resources.ftpserver.FTPServer.port
Rappresenta la seconda coordinata per la comunicazione con il server FTP: port
Referenced by resources.ftpserver.FTPServer.setCoords, resources.ftpserver.FTPServer.setCoordsAM, resources.ftpserver.FTPServer.getPort.
Boolean resources.ftpserver.FTPServer.isLoggedIn
Rappresenta un flag booleano indicante se o se non si è loggati nel server
Referenced by resources.ftpserver.FTPServer.getIsLoggedIn.
resources.ftpserver.FTPServer.FTPServer(final Boolean showServerReplies, final Boolean isNoOp, final Boolean isLogBidirectional)
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe showServerReplies Flag booleano indicante se o se non visualizzare su console le risposte da parte del server isNoOp Flag booleano indicante se o se non il server supporta la funzionalità keep alive: noop isLogBidirectional Flag booleano indicante se o se non il server supporta la funzionalità di login/logout bidirezionale FTPServer.manager FTPServer.keeper FTPServer.timer FTPServer.backupReplies FTPServer.host FTPServer.port FTPServer.isLoggedIn FTPServer.startKeeper
References resources.ftpserver.FTPServer.manager, resources.ftpserver.FTPServer.startKeeper.
Boolean resources.ftpserver.FTPServer.setCoords(String host, Integer port)
Imposta le coordinate del server FTP con il quale comunicare.
Il seguente metodo imposta le coordinate dal server FTP con il quale comunicare host La prima coordinata per la comunicazione con il server FTP: host port La seconda coordinata per la comunicazione con il server FTP: port Un valore booleano indicante la corretta esecuzione dell'impostazione delle coordinate del server FTP con il quale comunicare La connessione con il server non deve essere attiva FTPServer.manager FTPServer.host FTPServer.port
References resources.ftpserver.Manager.getIsConnected, resources.ftpserver.FTPServer.host, resources.ftpserver.FTPServer.port.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState.
void resources.ftpserver.FTPServer.setCoordsAM(String host, Integer port)
Imposta le coordinate del server FTP con il quale comunicare.
Il seguente metodo imposta le coordinate dal server FTP con il quale comunicare host La prima coordinata per la comunicazione con il server FTP: host port La seconda coordinata per la comunicazione con il server FTP: port La connessione con il server non deve essere attiva FTPServer.manager FTPServer.host FTPServer.port
References resources.ftpserver.Manager.getIsConnected, resources.ftpserver.FTPServer.host, resources.ftpserver.FTPServer.port.
Boolean resources.ftpserver.FTPServer.connect()
Tenta di stabilire una connessione con il server FTP.
Il seguente metodo tenta di stabilire una connessione con il server FTP Un valore booleano indicante la corretta esecuzione del tentativo di stabilire una connessione con il server FTP La connessione con il server non deve essere attiva FTPServer.manager FTPServer.host FTPServer.port FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsConnected, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex, resources.ftpserver.Manager.setIsConnected.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.stableState.
void resources.ftpserver.FTPServer.connectAM()
Tenta di stabilire una connessione con il server FTP.
Il seguente metodo tenta di stabilire una connessione con il server FTP La connessione con il server non deve essere attiva FTPServer.manager FTPServer.host FTPServer.port FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsConnected, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex, resources.ftpserver.Manager.setIsConnected.
Boolean resources.ftpserver.FTPServer.login(String username, String password)
Tenta di effettuare il login sul server FTP.
Il seguente metodo tenta di effettuare il login sul server FTP username Username per effettuare il login password Password per effettuare il login Un valore booleano indicante la corretta esecuzione del tentativo di effettuare il login sul server FTP La connessione con il server deve essere attiva Il login sul server non deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsConnected, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Referenced by resources.ftpserver.FTPServer.loginAM, guiGelataio.InterfacciaPrincipaleGalataio.stableState.
void resources.ftpserver.FTPServer.loginAM(String username, String password)
Tenta di effettuare il login sul server FTP.
Il seguente metodo tenta di effettuare il login sul server FTP username Username per effettuare il login password Password per effettuare il login La connessione con il server deve essere attiva Il login sul server non deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsConnected, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex, resources.ftpserver.FTPServer.login.
String resources.ftpserver.FTPServer.getCurrentDirectory()
Ottiene la directory di lavoro corrente.
Il seguente metodo ottiene la directory di lavoro corrente La directory di lavoro corrente Il login sul server deve essere già stato eseguito FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsConnected, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
String resources.ftpserver.FTPServer.getCurrentDirectoryAM()
Ottiene la directory di lavoro corrente.
Il seguente metodo ottiene la directory di lavoro corrente La directory di lavoro corrente Il login sul server deve essere già stato eseguito FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Boolean resources.ftpserver.FTPServer.setCurrentDirectory(String directoryPath)
Cambia la directory di lavoro corrente.
Il seguente metodo cambia la directory di lavoro corrente directoryPath La nuova directory di lavoro corrente Un valore booleano indicante il corretto cambiamento della directory di lavoro corrente Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma2ActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonConfermaActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonEliminaCronologiaOrdinazioniActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro1ActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorinoActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonScaricaCronologiaOrdinazioniActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer, resources.cronology.CronologyUpdater.run, resources.ordine.OrdineUpdater.run.
void resources.ftpserver.FTPServer.setCurrentDirectoryAM(String directoryPath)
Cambia la directory di lavoro corrente.
Il seguente metodo cambia la directory di lavoro corrente directoryPath La nuova directory di lavoro corrente Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
String [] resources.ftpserver.FTPServer.getListElements()
Ottiene una lista di elementi presenti nella directory di lavoro corrente.
Il seguente metodo ottiene una lista di elementi presenti nella directory di lavoro corrente Una lista di elementi presenti nella directory di lavoro corrente Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Referenced by resources.ftpserver.FTPServer.downloadFileAM, guiGelataio.InterfacciaPrincipaleGalataio.jButtonEliminaCronologiaOrdinazioniActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonScaricaCronologiaOrdinazioniActionPerformed, resources.cronology.CronologyUpdater.run, resources.ordine.OrdineUpdater.run.
String [] resources.ftpserver.FTPServer.getListElementsAM()
Ottiene una lista di elementi presenti nella directory di lavoro corrente.
Il seguente metodo ottiene una lista di elementi presenti nella directory di lavoro corrente Una lista di elementi presenti nella directory di lavoro corrente Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Boolean resources.ftpserver.FTPServer.uploadUniqueFile(InputStream uploadStream)
Carica un file con nome unico dal client al server.
Il seguente metodo carica un file con nome unico dal client al server uploadStream Il file da caricare dal client al server Un valore booleano indicante il corretto caricamento del file con nome unico dal client al server Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorinoActionPerformed.
void resources.ftpserver.FTPServer.uploadUniqueFileAM(InputStream uploadStream)
Carica un file con nome unico dal client al server.
Il seguente metodo carica un file con nome unico dal client al server uploadStream Il file da caricare dal client al server Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Boolean resources.ftpserver.FTPServer.uploadFile(String nameRemoteFile, InputStream uploadStream)
Carica un file dal client al server.
Il seguente metodo carica un file dal client al server nameRemoteFile Nome da assegnare al file salvato nella memoria del server uploadStream Il file da caricare dal client al server Un valore booleano indicante il corretto caricamento del file dal client al server Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonConferma2ActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonConfermaActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonIndietro1ActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorinoActionPerformed, resources.ftpserver.Keeper.run, resources.ordine.OrdineUpdater.run, resources.ftpserver.FTPServer.updateFileAppending, resources.ftpserver.FTPServer.updateFileAppendingAM.
void resources.ftpserver.FTPServer.uploadFileAM(String nameRemoteFile, InputStream uploadStream)
Carica un file dal client al server.
Il seguente metodo carica un file dal client al server nameRemoteFile Nome da assegnare al file salvato nella memoria del server uploadStream Il file da caricare dal client al server Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Boolean resources.ftpserver.FTPServer.downloadFile(String nameRemoteFile, OutputStream downloadStream)
Scarica un file dal server al client.
Il seguente metodo scarica un file dal server al client nameRemoteFile Nome del file salvato nella memoria del server da scaricare nella memoria locale downloadStream File salvato nella memoria locale utilizzato come target per lo scaricamento dei dati Un valore booleano indicante il corretto scaricamento di un file dal server al client Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonScaricaCronologiaOrdinazioniActionPerformed, guiGelataio.InterfacciaPrincipaleGalataio.loadFromServer, resources.ordine.OrdineUpdater.run, resources.ftpserver.FTPServer.updateFileAppending, resources.ftpserver.FTPServer.updateFileAppendingAM.
void resources.ftpserver.FTPServer.downloadFileAM(String nameRemoteFile, OutputStream downloadStream)
Scarica un file dal server al client.
Il seguente metodo scarica un file dal server al client nameRemoteFile Nome del file salvato nella memoria del server da scaricare nella memoria locale downloadStream File salvato nella memoria locale utilizzato come target per lo scaricamento dei dati Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.FTPServer.getListElements, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Boolean resources.ftpserver.FTPServer.updateFileAppending(String nameRemoteFile, InputStream uploadStream, OutputStream downloadStream, PrintWriter localWriteStream, String toAppend)
Aggiorna un file nel server dal client al server.
Il seguente metodo effettua un aggiornamento di un file già presente nella memoria del server con le informazioni di un file locale presente nella memoria del client nameRemoteFile Nome del file salvato nella memoria del server da aggiornare uploadStream Il file locale con le quali informazioni aggiornare il file salvato nella memoria del server downloadStream File salvato nella memoria locale utilizzato come target per lo scaricamento dei dati localWriteStream Stream per effettuare la scrittura di un file in locale toAppend Informazioni da scrivere nel file Un valore booleano indicante la corretta esecuzione dell'aggiornamento del file nel server Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.downloadFile() FTPServer.uploadFile()
References resources.ftpserver.FTPServer.downloadFile, resources.ftpserver.FTPServer.uploadFile.
void resources.ftpserver.FTPServer.updateFileAppendingAM(String nameRemoteFile, InputStream uploadStream, OutputStream downloadStream, PrintWriter localWriteStream, String toAppend)
Aggiorna un file nel server dal client al server.
Il seguente metodo effettua un aggiornamento di un file già presente nella memoria del server con le informazioni di un file locale presente nella memoria del client nameRemoteFile Nome del file salvato nella memoria del server da aggiornare uploadStream Il file locale con le quali informazioni aggiornare il file salvato nella memoria del server downloadStream File salvato nella memoria locale utilizzato come target per lo scaricamento dei dati localWriteStream Stream per effettuare la scrittura di un file in locale toAppend Informazioni da scrivere nel file Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.downloadFile() FTPServer.uploadFile()
References resources.ftpserver.FTPServer.downloadFile, resources.ftpserver.FTPServer.uploadFile.
Boolean resources.ftpserver.FTPServer.logout()
Tenta di effettuare il logout dal server.
Il seguente metodo tenta di effettuare il logout dal server Un valore booleano indicante la corretta esecuzione del tentativo di effettuare il logout dal server Il login sul server deve essere già stato eseguito FTPServer.manager FTPServer.isLoggedIn()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsLogBidirectional, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Referenced by resources.ftpserver.FTPServer.logoutAM.
void resources.ftpserver.FTPServer.logoutAM()
Tenta di effettuare il logout dal server.
Il seguente metodo tenta di effettuare il logout dal server Il login sul server deve essere già stato eseguito FTPServer.manager FTPServer.isLoggedIn()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsLogBidirectional, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex, resources.ftpserver.FTPServer.logout.
Boolean resources.ftpserver.FTPServer.disconnect()
Tenta di effettuare la disconnesione dal server.
Il seguente metodo tenta di effattuare la disconnesione dal server Un valore booleano indicante la corretta esecuzione del tentativo di disconnessione dal server La connessione con il server deve essere attiva FTPServer.manager FTPServer.isLoggedIn FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsConnected, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex, resources.ftpserver.Manager.setIsConnected.
void resources.ftpserver.FTPServer.disconnectAM()
Tenta di effettuare la disconnesione dal server.
Il seguente metodo tenta di effattuare la disconnesione dal server La connessione con il server deve essere attiva FTPServer.manager FTPServer.isLoggedIn FTPServer.getAndPrintServerReply()
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getIsConnected, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex, resources.ftpserver.Manager.setIsConnected.
Boolean resources.ftpserver.FTPServer.deleteFile(String nameRemoteFile)
Elimina un file dal server.
Il seguente metodo effettua l'eliminazione di un file dalla memoria del server nameRemoteFile Nome del file salvato nella memoria del server da eliminare Un valore booleano indicante la corretta esecuzione dell'eliminazione del file dalla memoria del server Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager
References resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
Referenced by resources.ftpserver.FTPServer.deleteFileAM, guiGelataio.InterfacciaPrincipaleGalataio.jButtonEliminaCronologiaOrdinazioniActionPerformed, resources.ordine.OrdineUpdater.run.
void resources.ftpserver.FTPServer.deleteFileAM(String nameRemoteFile)
Elimina un file dal server.
Il seguente metodo effettua l'eliminazione di un file dalla memoria del server nameRemoteFile Nome del file salvato nella memoria del server da eliminare Il login sul server deve essere già stato eseguito FTPServer.isLoggedIn FTPServer.manager
References resources.ftpserver.FTPServer.deleteFile, resources.ftpserver.FTPServer.getAndPrintServerReply, resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getServerMutex.
String resources.ftpserver.FTPServer.getHost()
Ritorna il valore dell'attributo FTPServer.host.
Il valore dell'attributo FTPServer.host FTPServer.host
References resources.ftpserver.FTPServer.host.
Integer resources.ftpserver.FTPServer.getPort()
Ritorna il valore dell'attributo FTPServer.port.
Il valore dell'attributo FTPServer.port FTPServer.port
References resources.ftpserver.FTPServer.port.
Boolean resources.ftpserver.FTPServer.getIsLoggedIn()
Ritorna il valore dell'attributo FTPServer.isLoggedIn.
Il valore dell'attributo FTPServer.isLoggedIn FTPServer.isLoggedIn
References resources.ftpserver.FTPServer.isLoggedIn.
Boolean resources.ftpserver.FTPServer.getIsConnected()
Ritorna il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getIsConnected()
Il seguente metodo ritorna il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getIsConnected() Il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getIsConnected() resources.ftpserver.Manager FTPServer.manager
References resources.ftpserver.Manager.getIsConnected.
Boolean resources.ftpserver.FTPServer.getIsNoOp()
Ritorna il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getIsNoOp()
Il seguente metodo ritorna il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getIsNoOp() Il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getIsNoOp() resources.ftpserver.Manager FTPServer.manager
References resources.ftpserver.Manager.getIsNoOp.
Boolean resources.ftpserver.FTPServer.getShowServerReplies()
Ritorna il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getShowServerReplies()
Il seguente metodo ritorna il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getShowServerReplies() Il valore ottenuto attraverso l'invocazione del metodo resources.ftpserver.Manager.getShowServerReplies() resources.ftpserver.Manager FTPServer.manager
References resources.ftpserver.Manager.getShowServerReplies.
FTPClient resources.ftpserver.FTPServer.getServerBackdoor()
References resources.ftpserver.Manager.getServer.
void resources.ftpserver.FTPServer.startKeeper()
Avvia il thread rappresentato dall'oggetto FTPServer.keeper.
Il seguente metodo è necessario per avviare il thread rappresentato dall'oggetto FTPServer.keeper FTPServer.timer FTPServer.keeper
References resources.ftpserver.FTPServer.keeper.
Referenced by resources.ftpserver.FTPServer.FTPServer.
void resources.ftpserver.FTPServer.getAndPrintServerReply()
Visualizza su console le eventuali risposte del server a comandi.
Il seguente metodo visualizza su console le eventuali risposte del server dopo lo svolgimento di azioni con esso. E' consigliabile richiamare questo metodo dopo ogni comando inviato al server, in quanto eventuali messaggi generati da un comando sovrascrivono quelli precedenti FTPServer.manager FTPServer.backupReplies
References resources.ftpserver.Manager.getServer, resources.ftpserver.Manager.getShowServerReplies.
Referenced by resources.ftpserver.FTPServer.connect, resources.ftpserver.FTPServer.connectAM, resources.ftpserver.FTPServer.deleteFile, resources.ftpserver.FTPServer.deleteFileAM, resources.ftpserver.FTPServer.disconnect, resources.ftpserver.FTPServer.disconnectAM, resources.ftpserver.FTPServer.downloadFile, resources.ftpserver.FTPServer.downloadFileAM, resources.ftpserver.FTPServer.getCurrentDirectory, resources.ftpserver.FTPServer.getCurrentDirectoryAM, resources.ftpserver.FTPServer.getListElements, resources.ftpserver.FTPServer.getListElementsAM, resources.ftpserver.FTPServer.login, resources.ftpserver.FTPServer.loginAM, resources.ftpserver.FTPServer.logout, resources.ftpserver.FTPServer.logoutAM, resources.ftpserver.FTPServer.setCurrentDirectory, resources.ftpserver.FTPServer.setCurrentDirectoryAM, resources.ftpserver.FTPServer.uploadFile, resources.ftpserver.FTPServer.uploadFileAM, resources.ftpserver.FTPServer.uploadUniqueFile, resources.ftpserver.FTPServer.uploadUniqueFileAM.
static Boolean resources.ftpserver.FTPServer.uploadFile(FTPClient server, String nameRemoteFile, InputStream uploadStream)
Carica un file dal client al server.
Il seguente metodo carica un file dal client al server server Server nameRemoteFile Nome da assegnare al file salvato nella memoria del server uploadStream Il file da caricare dal client al server Il login sul server deve essere già stato eseguito Un valore booleano indicante il corretto caricamento del file dal client al server