resources::ordine::xml::generatorxmlv2::GeneratorXMLOrdinev2
Document resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.document
Rappresenta il documento "virtuale" sul quale andremo a creare il nostro albero DOM
Referenced by resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.createDOMTree, resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.get.
resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.GeneratorXMLOrdinev2()
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe GeneratorXMLOrdinev2.document
void resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.createDOMTree(ArrayList< Ordine > data)
Crea l'albero DOM.
data Lista di oggetti da convertire in "nodi dell'albero DOM" ParserConfigurationException GeneratorXMLOrdinev2.createDocument() GeneratorXMLOrdinev2.document
References resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.createDocument, resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.document.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorinoActionPerformed.
void resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.applyDOMonXMLFile(String filenameNpath)
Crea l'effettivo file XML sulla base dell'albero DOM.
filenameNpath Path del file XML di salvataggio TransformerConfigurationException TransformerException GeneratorXMLOrdinev2.document
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonInoltroAlFattorinoActionPerformed.
void resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.createDocument()
Crea il documento "virtuale" supporto per il nostro albero DOM.
ParserConfigurationException GeneratorXMLOrdinev2.document
Referenced by resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.createDOMTree.
Element resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.get(Ordine singleElement)
Converte un oggetto in "nodo dell'albero DOM".
singleElement L'oggetto da convertire in "nodo dell'albero DOM" Il nodo dell'albero DOM (L'oggetto convertito in) GeneratorXMLOrdinev2.document
References resources.ordine.xml.generatorxmlv2.GeneratorXMLOrdinev2.document.