resources::orariodelnegozio::xml::generatorxml::GeneratorXMLModificaOrarioDelNegozio
Document resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.document
Rappresenta il documento "virtuale" sul quale andremo a creare il nostro albero DOM
Referenced by resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.createDOMTree, resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.get.
resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.GeneratorXMLModificaOrarioDelNegozio()
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe GeneratorXMLModificaOrarioDelNegozio.document
void resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.createDOMTree(ArrayList< OrarioDelNegozio > data)
Crea l'albero DOM.
data Lista di oggetti da convertire in "nodi dell'albero DOM" ParserConfigurationException GeneratorXMLModificaOrarioDelNegozio.createDocument() GeneratorXMLModificaOrarioDelNegozio.document
References resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.createDocument, resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.document.
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonConfermaActionPerformed.
void resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.applyDOMonXMLFile(String filenameNpath)
Crea l'effettivo file XML sulla base dell'albero DOM.
filenameNpath Path del file XML di salvataggio TransformerConfigurationException TransformerException GeneratorXMLModificaOrarioDelNegozio.document
Referenced by guiGelataio.InterfacciaPrincipaleGalataio.jButtonConfermaActionPerformed.
void resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.createDocument()
Crea il documento "virtuale" supporto per il nostro albero DOM.
ParserConfigurationException GeneratorXMLModificaOrarioDelNegozio.document
Referenced by resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.createDOMTree.
Element resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.get(OrarioDelNegozio singleElement)
Converte un oggetto in "nodo dell'albero DOM".
singleElement L'oggetto da convertire in "nodo dell'albero DOM" Il nodo dell'albero DOM (L'oggetto convertito in) GeneratorXMLModificaOrarioDelNegozio.document
References resources.orariodelnegozio.xml.generatorxml.GeneratorXMLModificaOrarioDelNegozio.document.